language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build
  on:
    branch: master
  github_token:
    secure: WYY19bqpD0I9AXe42MkB/dAO7w5jh9N1VU7XvOZztnVsYWJpmkcrKerp7tGyokFhlAiZa6/pymis69JD6RphqaPmVud4Byadg3mcad8zU5QdPZFyAENnEk83Noz8dCSTB414Xznu4GPpHSGkZy6fpFRdMbJd+HISXq4IM3SkngdG99eYl7EsTe8v03AFUoT44l58co6TBzOPYjNV6uqLbu/2AKE/Pc0oIvbDumJCIeSFS6XH+dyWcWuxFaTQd7eUtYW70cyzTszCAX57Rof54EZMnu1FCZdbEwDSVKLkhRMN1esT0uOESYrCYZSBwyZGrPfVboVC1ftQhfkEJREqXveJN+mi7iE4QtIVsEFSIFU2x56IIWZr+pvCrkEymVaAdedr1MqOm11QmdyZxYRIkFWyYNZa0cMfzbe2KtIyQyFwxyN2C0v3Du11XSioMtddTuynpUDrA5ECqzXtGhBLzXoIG2KqW5w78X9YniO5wEq87bpmbgRaN25mkyDtYORGYQRluf0P0PSMl4+AoOZu5FTOzwGWCwIbvkq619YTCqICynn4/u1AJzYuFixMtFSooPAgVqovuq8IvPowvowgmgnn2flQm0mpRu9a8kcsZaL7YltZFDp9SF5qv+gj4mMnsB7Gww+ykgqSOsHQWQlLU+wjrr2z7mjjmPMLhd7wfqg=
