language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build
  on:
    branch: master
  github-token:
    secure: X9mW0+BoiqIMr8yrSusSuel51kTKqhpwJYxNdZbpISM8kURVP2dY+vX+g6qICxPluudDy9jyyPYtjR2+1jGc0f9TWwb64AmjGbRgHMxadD8jMI9vgrRqOeOk+7tljfxbreIjUuoqqSJcpYOb8Qvu+L9lIirztdlZbm1OqcKJlI1v40l/LDJggCZ0473IxGenb9FSU+LlY+YBa1woss658MXl+3k6NIl4TYvFDcWI/mRukmqNd2wWbKTQlqNQxc6NajhEHQCzxRcHrbWDbmLkaRkbwA8TgmMgWtkKRPCOYaDhR5Fs95IADPhr+Hp7XPNADhUdTI9loBUgJ3sUDPN16Z0z06CKVhCDXm4uJi+aZR/gJ3pnLqBwewfhvPJ98RmkdvZSle4SuNMku2FvQrxw/5ir54mqqwqgM/es1yA4VcRbqFV8nDbfwP31D7QXXLWXvKMVDgwFZNJEES5HDNZUGmL+m4Cz1MF1Z3X3jv582vqEpRDu+0+nSjeoZTZ6Sl4Hl8WSNE4Qag4HtyPj889cMEvm/cQtUXiyEAq53OBU7Z1r2Av2kmHqm6Cv4Z/NgVgz8QuNNhElL0Q7yuhdfPiws+oL+PC/cFvbNa41GpnDq5DYW0flstIszwupBddgIQ0ci5NnM9VH3o8aIXV3YFZmDJ5IfefTC5gjGe0GKyxwIOA=
